/**
 * Analytics & Scoring Type Definitions
 * These are DERIVED/CALCULATED values — not from the API directly.
 */

import type { CocPlayer, CocClan } from "./coc-api";

// ─── Data Source Labels ───────────────────────────────────────

export type DataSource =
  | "official_api"      // Direct from CoC API
  | "static_game_db"    // From our game database
  | "calculated"        // Derived from API + static data
  | "ai_generated"      // Generated by Gemini
  | "partial"           // Incomplete due to API limitations
  | "unavailable";      // API does not provide this data

export interface DataPoint<T> {
  value: T;
  source: DataSource;
  note?: string; // e.g. "API does not provide building levels"
}

// ─── Item Progress ────────────────────────────────────────────

export interface ItemProgress {
  name: string;
  apiName: string;
  currentLevel: number;
  maxLevel: number;
  completionPercent: number;
  isMaxed: boolean;
  village?: "home" | "builderBase";
  category?: string;
}

// ─── Aggregated Progress ─────────────────────────────────────

export interface CategoryProgress {
  category: string;
  completionPercent: number;
  totalItems: number;
  maxedItems: number;
  source: DataSource;
  items: ItemProgress[];
}

export interface OverallProgress {
  overall: number; // Weighted average
  heroes: CategoryProgress;
  troops: CategoryProgress;
  spells: CategoryProgress;
  pets: CategoryProgress;
  equipment: CategoryProgress;
  // These cannot be calculated from API — noted as unavailable
  defenses: DataPoint<null>;
  walls: DataPoint<null>;
}

// ─── Rush Analysis ────────────────────────────────────────────

export type RushRisk = "VERY_LOW" | "LOW" | "MEDIUM" | "HIGH" | "VERY_HIGH";

export interface RushCategory {
  category: string;
  expectedMinPercent: number; // What % should be done at this TH
  actualPercent: number;
  deficit: number; // expectedMin - actual (negative = rushed)
  isRushed: boolean;
}

export interface RushAnalysis {
  score: number; // 0-100, higher = more rushed
  risk: RushRisk;
  categories: RushCategory[];
  summary: string;
  source: DataSource;
}

// ─── War Readiness ────────────────────────────────────────────

export interface WarReadiness {
  score: number; // 0-100
  heroScore: number;
  equipmentScore: number;
  troopScore: number;
  spellScore: number;
  label: "NOT_READY" | "WEAK" | "AVERAGE" | "STRONG" | "ELITE";
}

// ─── Upgrade Priority ─────────────────────────────────────────

export type PriorityLevel = "VERY_HIGH" | "HIGH" | "MEDIUM" | "LOW" | "SKIP";

export interface UpgradePriority {
  name: string;
  category: string;
  currentLevel: number;
  maxLevel: number;
  priority: PriorityLevel;
  priorityScore: number; // 0-100
  reasons: string[]; // Why this priority
  estimatedDurationDays?: number;
}

// ─── TH Transition Readiness ──────────────────────────────────

export interface ThTransitionReadiness {
  currentTh: number;
  nextTh: number;
  readinessScore: number; // 0-100
  recommendation: "READY" | "ALMOST" | "WAIT" | "NOT_READY";
  breakdown: {
    category: string;
    score: number;
    status: string;
  }[];
  doBeforeUpgrade: string[];
  canUpgradeNow: string[];
}

// ─── Upgrade Time Estimate ────────────────────────────────────

export interface UpgradeTimeEstimate {
  estimatedDays: number;
  isPartialEstimate: boolean; // True if some data was missing
  assumptions: {
    builders: number;
    laboratoryAvailable: boolean;
    parallelBuilds: boolean;
    dailyBuildTime: number; // hours
  };
  disclaimer: string;
}

// ─── Full Player Analysis ─────────────────────────────────────

export interface PlayerAnalysis {
  // Raw API data (sourced from official API)
  player: CocPlayer;

  // Calculated
  progress: OverallProgress;
  rush: RushAnalysis;
  warReadiness: WarReadiness;
  upgradePriorities: UpgradePriority[];
  thTransition?: ThTransitionReadiness;
  upgradeTimeEstimate?: UpgradeTimeEstimate;

  // Metadata
  analyzedAt: Date;
  cached: boolean;
  cachedAt?: Date;
  gameVersion: string;
}

// ─── Clan Analysis ────────────────────────────────────────────

export interface ClanMemberAnalysis {
  tag: string;
  name: string;
  townHallLevel: number;
  trophies: number;
  role: string;
  warStars?: number;
  // Requires fetching each member separately — expensive
  // Only included if pre-fetched or cached
  heroProgress?: number;
  warReadiness?: number;
  rushScore?: number;
}

export interface ClanPowerScore {
  overall: number;
  offensiveStrength: number;
  defensiveStrength: number;
  heroStrength: number;
  warReadiness: number;
  thBalance: number;
  activity: number;
  source: DataSource;
}

export interface ClanAnalysis {
  clan: CocClan;
  powerScore: ClanPowerScore;
  thDistribution: Record<string, number>; // {"15": 3, "16": 8, ...}
  memberAnalyses: ClanMemberAnalysis[];
  analyzedAt: Date;
  cached: boolean;
  gameVersion: string;
}

// ─── AI Response ──────────────────────────────────────────────

export interface AiAnalysis {
  summary: string;
  strengths: string[];
  weaknesses: string[];
  recommendations: string[];
  nextActions: string[];
  generatedAt: Date;
  model: string;
  // Guard: only contains info from provided structured data
  dataSourcesUsed: DataSource[];
}
